###############################################
# Group 8
# Assignment 2
#
# List Processing in the Mini Language
################################################

VIEW=more

all: view-part1 build view-func1 view-func2 view-part2 run-part2 clean
.PHONY : all

compile-static:
	echo "no need to compile"

compile-dynamic:
	echo "no need to compile"

run: oop_interpreterext.py
	python oop_interpreterext.py


clean:
	-@rm parser.out 2> /dev/null
	-@rm parsetab.* 2> /dev/null
	-@rm *.pyc 2> /dev/null
